openapi: 3.0.0
info:
  title: Connpass API
  version: 0.0.1

servers:
    - url: https://connpass.com/api
      description: Connpass API へ接続

paths:
  /v1/event:
    get:
      summary: イベントサーチ
      description: |
        [connpass API リファレンス](https://connpass.com/about/api/)
      parameters:
        - in: query
          name: count
          description: 取得件数
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - in: query
          name: event_id
          description: イベントID
          schema:
            type: array
            items:
              type: integer
          style: form
          explode: false
        - in: query
          name: format
          description: レスポンス形式
          schema:
            type: string
            default: json
        - in: query
          name: keyword
          description: キーワード (AND)
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - in: query
          name: keyword_or
          description: キーワード (OR)
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - in: query
          name: nickname
          description: 参加者のニックネーム
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - in: query
          name: order
          description: 検索結果の表示順
          schema:
            enum:
              - 1
              - 2
              - 3
            default: 1
        - in: query
          name: owner_nickname
          description: 管理者のニックネーム
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - in: query
          name: series_id
          description: グループID
          schema:
            type: array
            items:
              type: integer
          style: form
          explode: false
        - in: query
          name: start
          description: 検索の開始位置
          schema:
            type: integer
            default: 1
        - in: query
          name: ym
          description: イベント開催年月
          schema:
            type: array
            items:
              type: string
              pattern: '^\d{4}(0[1-9]|1[0-2])$'
          style: form
          explode: false
        - in: query
          name: ymd
          description: イベント開催年月日
          schema:
            type: array
            items:
              type: string
              pattern: '^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])$'
          style: form
          explode: false
      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventResponse'



components:
  schemas:
    Event:
      type: object
      properties:
        accepted:
          type: integer
          description: 参加者数
        address:
          type: string
          description: 開催場所
        catch:
          type: string
          description: キャッチ
        description:
          type: string
          description: 概要(HTML形式)
        ended_at:
          type: string
          format: date-time
          description: イベント開催日時 (ISO-8601形式)
        event_id:
          type: integer
          description: イベントID
        event_type:
          type: string
          description: イベント参加タイプ
        event_url:
          type: string
          description: connpass.com 上のURL
        hash_tag:
          type: string
          description: Twitterのハッシュタグ
        lat:
          type: number
          format: double
          description: 開催会場の緯度
        limit:
          type: integer
          description: 定員
        lon:
          type: number
          format: double
          description: 開催会場の経度
        owner_display_name:
          type: string
          description: 管理者の表示名
        owner_id:
          type: integer
          description: 管理者のID
        owner_nickname:
          type: string
          description: 管理者のニックネーム
        place:
          type: string
          description: 開催会場
        series:
          description: 検索結果のイベントリスト
          oneOf:
            - $ref: '#/components/schemas/Series'
        started_at:
          type: string
          format: date-time
          description: イベント開催日時 (ISO-8601形式)
        title:
          type: string
          description: タイトル
        updated_at:
          type: string
          format: date-time
          description: 更新日時 (ISO-8601形式)
        waiting:
          type: integer
          description: 補欠者数

    GetEventResponse:
      type: object
      properties:
        events:
          description: 検索結果のイベントリスト
          type: array
          items:
            $ref: '#/components/schemas/Event'
        results_available:
          type: integer
          description: 検索結果の総件数
        results_returned:
          type: integer
          description: 含まれる検索結果の件数
        results_start:
          type: integer
          description: 検索の開始位置

    Series:
      type: object
      properties:
        id:
          type: integer
          description: グループID
        title:
          type: string
          description: グループタイトル
        url:
          type: string
          format: uri
          description: グループのconnpass.com 上のURL
