// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XAppData.DB;

#nullable disable

namespace XAppApi.Migrations
{
    [DbContext(typeof(XAppDbContext))]
    [Migration("20220813050810_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("XAppData.DB.Entities.ToDoTaskDbEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("todo_tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
