openapi: 3.0.1
info:
  title: AndroidRecipe 用WebAPI
  description: |
    ## UML
    * [ToDo関連フロー](https://tentashion.github.io/AndroidRecipe/uml/ToDo%E9%96%A2%E9%80%A3%E3%83%95%E3%83%AD%E3%83%BC.png)
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: モックサーバーへの接続
paths:
  /v1/todo:
    get:
      summary: 登録したToDo 一覧の取得
      operationId: v1TodoGET
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                items:
                - id: "1"
                  is_finish: false
                  title: やることその１
                  update_date: 2020-01-10T23:57:49+09:00
                - id: "2"
                  is_finish: true
                  title: やることその２
                  update_date: 2020-01-10T23:57:49+09:00
      x-swagger-router-controller: Default
    post:
      summary: ToDo 新規登録
      operationId: v1TodoPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
            example:
              title: やること名
        required: true
      responses:
        "200":
          description: 成功
      x-swagger-router-controller: Default
  /v1/todo/{id}:
    put:
      summary: ToDo 編集
      operationId: v1TodoIdPUT
      parameters:
      - name: id
        in: path
        description: 識別番号
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
            example:
              is_finish: false
              title: やること名
        required: true
      responses:
        "200":
          description: 成功
      x-swagger-router-controller: Default
    delete:
      summary: ToDo 削除
      operationId: v1TodoIdDELETE
      parameters:
      - name: id
        in: path
        description: 識別番号
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 成功
      x-swagger-router-controller: Default
components:
  schemas:
    ToDo:
      type: object
      properties:
        id:
          type: string
          description: 識別番号
        is_finish:
          type: boolean
          description: 完了フラグ
        title:
          type: string
          description: ToDo タイトル
        update_date:
          type: string
          description: 更新日時
          format: date-time
      example:
        is_finish: true
        id: id
        title: title
        update_date: 2000-01-23T04:56:07.000+00:00
    inline_response_200:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ToDo'
      example:
        items:
        - is_finish: true
          id: id
          title: title
          update_date: 2000-01-23T04:56:07.000+00:00
        - is_finish: true
          id: id
          title: title
          update_date: 2000-01-23T04:56:07.000+00:00
