# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  # ビルドの実行
  lane :build do
    build_ios_app(
      scheme: "App"
    )
  end

  # 自動テストの実行
  lane :tests do
    run_tests(
      scheme: "App",
      workspace: "App.xcworkspace"
    )
  end
end
