@startuml architecture

actor User as user
node "Android Native" as android
node "Electron"
node "Ionic + Capacitor" as base
node "iOS Native" as ios



user -> base
base -up-> android
base -> Electron
base -down-> ios

@enduml
