platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

def hyperion
  pod 'HyperioniOS/Core', '1.1.0', :configurations => ['Debug']

  pod 'HyperioniOS/AttributesInspector', '1.1.0', :configurations => ['Debug']
  pod 'HyperioniOS/Measurements', '1.1.0', :configurations => ['Debug']
  pod 'HyperioniOS/SlowAnimations', '1.1.0', :configurations => ['Debug']
end

def ui
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
end


target 'App' do
  capacitor_pods
  # Add your Pods here
  hyperion
  ui
end

target 'AppPreview' do
  capacitor_pods
  # Add your Pods here
  hyperion
  ui
end
