name: App
options:
  deploymentLanguage: Japan
  groupSortPosition: top
packages:
  mktools_ios:
    github: tshion/mktools_lab
    version: 2022.02.23
settings:
  PRODUCT_BUNDLE_IDENTIFIER: work.shion.xapprecipe
targetTemplates:
  appbase:
    dependencies:
      - package: mktools_ios
      - sdk: WebKit.framework
    deploymentTarget: "13.0"
    platform: iOS
    preBuildScripts:
      - path: scripts/format.sh
        name: Run Format
      - name: Generate by R.swift
        script: |
          "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
        inputFiles:
          - "$TEMP_DIR/rswift-lastrun"
        outputFiles:
          - "$SRCROOT/R.generated.swift"
    postBuildScripts:
      - path: scripts/lint.sh
        name: Run Lint
    sources:
      - path: App
        excludes:
          - "public/*"
      - path: "App/public"
        type: folder
      - path: "R.generated.swift"
        optional: true
    type: application


targets:
  App:
    templates:
      - appbase
  AppPreview:
    templates:
      - appbase
    sources:
      - AppPreview
  AppTests:
    dependencies:
      - target: App
    platform: iOS
    settings:
      INFOPLIST_FILE: AppTests/info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/App.app/App
    sources:
      - AppTests
    type: bundle.unit-test
